import React, { Component } from 'react';
import { IRecipe } from '../interfaces/recipe.interface';
import 'react-toastify/dist/ReactToastify.css';
import { ICustomer } from '../interfaces/customer.interface';
interface ICartItem extends IRecipe {
    cartId: string;
    tax_rate: number | undefined;
    vat_type: string;
    discount: number | undefined;
    quantity: number | undefined;
}
type Props = {
    settings: any;
};
type State = {
    recipes: IRecipe[];
    items: IRecipe[];
    customers: ICustomer[];
    customer: ICustomer | undefined;
    customerName: string | null;
    customerEmail: string | null;
    customerMobile: string | null;
    customerCity: string | null;
    customerBuilding: string | null;
    customerStreet: string | null;
    customerFloor: string | null;
    customerApartment: string | null;
    cart: ICartItem[];
    total: number;
    subtotal: number;
    tax: number | undefined;
    vatType: string;
    deliveryCharge: number | undefined;
    discount: number | undefined;
    hasaudio: boolean | undefined;
    tenderAmount: number | undefined;
    searchValue: string | null;
    remarks: string | null;
    orderType: string;
    isFullScreen: boolean;
    isLoading: boolean;
    isLoadingCategories: boolean;
    isPaid: boolean;
    selectItem: string;
};
declare class PointOfSale extends Component<Props, State> {
    constructor(props: Props);
    componentDidMount(): void;
    specialCustomerPrice: (prod: IRecipe) => number;
    getRecipes: () => void;
    storeOrder: () => void;
    reset: () => void;
    resetPos: () => void;
    handleDiscountChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
    handleTaxChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
    handleDeliveryChargeChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
    updateItemPrice: (event: React.ChangeEvent<HTMLInputElement>, item: ICartItem) => void;
    updateItemQtyByClick: (event: any, item: ICartItem, qty: number) => void;
    toggleFullScreen: () => void;
    goToDashboard: () => void;
    calculateItemPrice: (item: ICartItem) => number;
    calculateTotal: () => void;
    getVat: () => number;
    getTaxAmount: () => number;
    getTotalTax: () => number;
    getChangeAmount: () => number;
    handleTenderAmountChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
    handleRemarksChange: (event: React.FormEvent<HTMLTextAreaElement>) => void;
    removeItem: (item: ICartItem) => void;
    addToCart: (recipe: IRecipe) => void;
    handleSearchSubmit: (event: React.FormEvent<HTMLFormElement>) => void;
    handleSearchChange: (event: React.FormEvent<HTMLInputElement>) => void;
    handleVatTypeChange: (event: any) => void;
    handleCustomerSearchChange: (event: React.FormEvent<HTMLInputElement>) => void;
    setCustomer: (customer: ICustomer) => void;
    selectCustomer(customer: ICustomer): void;
    closeModal: (id: string) => void;
    getAppSettings: () => any;
    currencyFormatValue: (number: any) => any;
    receiptExchangeRate: () => any;
    removeCustomer(): void;
    isProductAvailable: (product: IRecipe) => boolean;
    updateItemQuantity: (event: React.ChangeEvent<HTMLInputElement>, item: ICartItem) => void;
    updateItemVatType: (item: ICartItem) => void;
    updateItemVAT: (event: React.ChangeEvent<HTMLInputElement>, item: ICartItem) => void;
    updateItemDiscount: (event: React.ChangeEvent<HTMLInputElement>, item: ICartItem) => void;
    togglePaidButton: () => void;
    createCustomer: (e: React.FormEvent<HTMLFormElement>) => void;
    handleSelectItem: (e: React.FormEvent<HTMLSelectElement>) => void;
    handleCustomerNameChange: (event: React.FormEvent<HTMLInputElement>) => void;
    handleCustomerEmailChange: (event: React.FormEvent<HTMLInputElement>) => void;
    handleCustomerMobileChange: (event: React.FormEvent<HTMLInputElement>) => void;
    handleCustomerCityChange: (event: React.FormEvent<HTMLInputElement>) => void;
    handleCustomerStreetChange: (event: React.FormEvent<HTMLInputElement>) => void;
    handleCustomerBuildingChange: (event: React.FormEvent<HTMLInputElement>) => void;
    handleCustomerFloorChange: (event: React.FormEvent<HTMLInputElement>) => void;
    handleCustomerApartmentChange: (event: React.FormEvent<HTMLInputElement>) => void;
    printInvoice: (data: any, settings: any) => void;
    modalCloseButton: () => React.ReactNode;
    modalCloseButtonWhite: () => React.ReactNode;
    handleOrderTypeChange: (event: React.ChangeEvent<HTMLSelectElement>) => void;
    isOrderDelivery: () => boolean;
    handleCloseModal: () => void;
    render(): JSX.Element;
}
export default PointOfSale;
