import React, { Component } from 'react';
import { ItemInterface } from '../interfaces/item.inteface';
import { ICategory } from '../interfaces/category.interface';
import 'react-toastify/dist/ReactToastify.css';
import { ICustomer } from '../interfaces/customer.interface';
interface ICartItem extends ItemInterface {
    cartId: string;
    tax_rate: number | undefined;
    vat_type: string;
    discount: number | undefined;
    quantity: number | undefined;
    old_tax_rate: number;
    old_vat_type: string;
    old_discount: number;
    old_quantity: number;
}
type Props = {
    settings: any;
    order: any;
};
type State = {
    orderId: string;
    orderNumber: string;
    categories: ICategory[];
    selectOption: ICategory[];
    products: ItemInterface[];
    showProducts: boolean;
    categoryName: string | null;
    customers: ICustomer[];
    customer: ICustomer | undefined;
    customerName: string | null;
    customerEmail: string | null;
    customerMobile: string | null;
    customerCity: string | null;
    customerBuilding: string | null;
    customerStreet: string | null;
    customerFloor: string | null;
    customerApartment: string | null;
    cart: ICartItem[];
    total: number;
    subtotal: number;
    tax: number | undefined;
    vatType: string;
    deliveryCharge: number | undefined;
    discount: number | undefined;
    hasaudio: boolean | undefined;
    tenderAmount: number | undefined;
    searchValue: string | null;
    remarks: string | null;
    orderType: string;
    isFullScreen: boolean;
    isLoading: boolean;
    isLoadingCategories: boolean;
    isPaid: boolean;
    selectItem: string;
};
declare class PointOfSaleEdit extends Component<Props, State> {
    constructor(props: Props);
    componentDidMount(): void;
    setupForEditing: () => Promise<void>;
    categoryClick: (category: ICategory) => void;
    backClick: () => void;
    specialCustomercost: (prod: ItemInterface) => number;
    getCategories: () => void;
    storeOrder: () => void;
    reset: () => void;
    resetPos: () => void;
    handleDiscountChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
    handleTaxChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
    handleDeliveryChargeChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
    updateItemcost: (event: React.ChangeEvent<HTMLInputElement>, item: ICartItem) => void;
    updateItemQtyByClick: (event: any, item: ICartItem, qty: number) => void;
    toggleFullScreen: () => void;
    goToOrderList: () => void;
    calculateItemcost: (item: ICartItem) => number;
    calculateTotal: () => void;
    getVat: () => number;
    getTaxAmount: () => number;
    getTotalTax: () => number;
    getChangeAmount: () => number;
    handleTenderAmountChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
    handleRemarksChange: (event: React.FormEvent<HTMLTextAreaElement>) => void;
    removeItem: (item: ICartItem) => void;
    addToCart: (recipe: ItemInterface) => void;
    handleSearchSubmit: (event: React.FormEvent<HTMLFormElement>) => void;
    handleSearchChange: (event: React.FormEvent<HTMLInputElement>) => void;
    handleVatTypeChange: (event: any) => void;
    handleCustomerSearchChange: (event: React.FormEvent<HTMLInputElement>) => void;
    setCustomer: (customer: ICustomer) => void;
    selectCustomer(customer: ICustomer): void;
    closeModal: (id: string) => void;
    getAppSettings: () => any;
    currencyFormatValue: (number: any) => any;
    receiptExchangeRate: () => any;
    removeCustomer(): void;
    isProductAvailable: (product: ItemInterface) => boolean;
    updateItemQuantity: (event: React.ChangeEvent<HTMLInputElement>, item: ICartItem) => void;
    updateItemVatType: (item: ICartItem) => void;
    updateItemVAT: (event: React.ChangeEvent<HTMLInputElement>, item: ICartItem) => void;
    updateItemDiscount: (event: React.ChangeEvent<HTMLInputElement>, item: ICartItem) => void;
    togglePaidButton: () => void;
    createCustomer: (e: React.FormEvent<HTMLFormElement>) => void;
    handleSelectItem: (e: React.FormEvent<HTMLSelectElement>) => void;
    handleCustomerNameChange: (event: React.FormEvent<HTMLInputElement>) => void;
    handleCustomerEmailChange: (event: React.FormEvent<HTMLInputElement>) => void;
    handleCustomerMobileChange: (event: React.FormEvent<HTMLInputElement>) => void;
    handleCustomerCityChange: (event: React.FormEvent<HTMLInputElement>) => void;
    handleCustomerStreetChange: (event: React.FormEvent<HTMLInputElement>) => void;
    handleCustomerBuildingChange: (event: React.FormEvent<HTMLInputElement>) => void;
    handleCustomerFloorChange: (event: React.FormEvent<HTMLInputElement>) => void;
    handleCustomerApartmentChange: (event: React.FormEvent<HTMLInputElement>) => void;
    printInvoice: (data: any, settings: any) => void;
    modalCloseButton: () => React.ReactNode;
    modalCloseButtonWhite: () => React.ReactNode;
    handleOrderTypeChange: (event: React.ChangeEvent<HTMLSelectElement>) => void;
    isOrderDelivery: () => boolean;
    handleCloseModal: () => void;
    render(): JSX.Element;
}
export default PointOfSaleEdit;
